### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by DKDiveDude** [PeterMacej/multiline-search-vs#2]
I just downloaded and installed your extension, while VS was closed.

After installing, and opening VS 2012 latest build, I do not find your "Find and Replace" menu anywhere, although I do see in Extensions that is is installed and enabled.

Please advise, thanks

**Comment by PeterMacej** [comment]
VS 2012? The extension doesn't work with this version. If you meant VS 2022, try to uninstall it, close VS, open VS and install it again. If still no help, try to install [Clear MEF Component Cache](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache) extension and clear teh MEF.

**Comment by DKDiveDude** [comment]
Yes I meant VS 2022. Tried what you suggested in order, finally clearing the MEF Component Cache solved it, thanks!
